---
deployment:
  tasks:
    - export DEPLOYPATH=/home/voidtech/public_html/
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -R website/* $DEPLOYPATH
    - /bin/cp website/.htaccess $DEPLOYPATH 2>/dev/null || :
    - /bin/cp website/robots.txt $DEPLOYPATH
    - /bin/cp website/sitemap.xml $DEPLOYPATH
